import "./globals.css";
import NavMenu from "./NavMenu";
import SearchBar from "@/components/SearchBar";
import NextAuthSessionProvider from "./providers/sessionProvider";
import AuthProvider from "./AuthProvider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <AuthProvider>
            <html lang="en">
                <body>
                    <NavMenu />
                    {children}
                </body>
            </html>
        </AuthProvider>
    );
}
